import React, { useState } from 'react';
import axios from 'axios';

const Payment = ({ enrollmentId, installmentAmount }) => {
  const [amount, setAmount] = useState(installmentAmount);

  const handlePayment = async () => {
    // Request a payment order from your backend
    const response = await axios.post('/api/razorpay_order', {
      amount,
      currency: 'INR',
      enrollmentId
    });

    const { orderId } = response.data;

    // Initialize Razorpay checkout
    const options = {
      key: 'rzp_test_gpnWAbxaa8RUyY',
      amount: amount * 100,
      currency: 'INR',
      name: 'Classpro',
      description: 'Course Installment Payment',
      order_id: orderId, // This is generated by Razorpay
      handler: async (response) => {
        // After successful payment, verify the payment and update the backend
        const result = await axios.post('/api/payment_success', {
          paymentId: response.razorpay_payment_id,
          enrollmentId,
          amount,
        });

        // Handle success response
        alert('Payment Successful');
      },
      prefill: {
        name: 'Student Name',
        email: 'student@example.com',
      },
    };

    const rzp = new window.Razorpay(options);
    rzp.open();
  };

  return (
    <div>
      <h3>Pay Installment</h3>
      <input
        type="number"
        value={amount}
        onChange={(e) => setAmount(e.target.value)}
      />
      <button onClick={handlePayment}>Pay Now</button>
    </div>
  );
};

export default Payment;
